Repository daweifeng/Practical-Resistance-Alliance-X, pull requests merged in 2019-04, with the labels that each got.

#12 update travis config
  .travis.yml
Labels: bug

#11 Changes on database and detail view
  .travis.yml
  app/controllers/category_controller.rb
  app/javascript/components/ToolkitViewer.js
  app/models/step.rb
  app/models/toolkit.rb
  app/views/category/display.html.erb
  db/migrate/20190405223824_create_steps.rb
  db/migrate/20190405224803_add_toolkit_reference_to_steps.rb
  db/migrate/20190405225819_create_toolkits.rb
  db/schema.rb
  db/seeds.rb
Labels: enhancement

#16 Create "New Toolkit" Page
  app/assets/javascripts/toolkit.coffee
  app/assets/stylesheets/newToolkit.scss
  app/assets/stylesheets/toolkit.scss
  app/controllers/category_controller.rb
  app/controllers/toolkit_controller.rb
  app/helpers/toolkit_helper.rb
  app/javascript/components/NewStepComponent.js
  app/javascript/components/NewToolkitPage.js
  app/javascript/components/ToolkitsListPage.js
  app/views/category/new.html.erb
  config/routes.rb
  db/seeds.rb
Labels: enhancement

#20 Add Navigation Tests
  app/controllers/category_controller.rb
  app/views/category/toolkit.html.erb
  config/routes.rb
  features/step_definitions/toolkit_steps.rb
  features/step_definitions/web_steps.rb
  features/support/paths.rb
  features/user_nav.feature
Labels: test

#25 Create User MVC
  Gemfile
  Gemfile.lock
  app/assets/javascripts/sessions.coffee
  app/assets/javascripts/users.coffee
  app/assets/stylesheets/scaffolds.scss
  app/assets/stylesheets/sessions.scss
  app/assets/stylesheets/users.scss
  app/controllers/application_controller.rb
  app/controllers/sessions_controller.rb
  app/controllers/users_controller.rb
  app/helpers/sessions_helper.rb
  app/helpers/users_helper.rb
  app/models/user.rb
  app/views/layouts/_navbar.html.erb
  app/views/layouts/application.html.erb
  app/views/sessions/create.html.erb
  app/views/sessions/destroy.html.erb
  app/views/sessions/new.html.erb
  app/views/users/_form.html.erb
  app/views/users/_user.json.jbuilder
  app/views/users/edit.html.erb
  app/views/users/index.html.erb
  app/views/users/index.json.jbuilder
  app/views/users/new.html.erb
  app/views/users/show.html.erb
  app/views/users/show.json.jbuilder
  config/routes.rb
  db/migrate/20190425182041_create_users.rb
  db/migrate/20190425232303_add_admin_to_users.rb
  db/schema.rb
  db/seeds.rb
Labels: enhancement

#26 User should login to create toolkits
  app/controllers/category_controller.rb
  features/support/paths.rb
  features/user_nav.feature
Labels: bug

#27 Add styles to toolkit pages
  app/assets/stylesheets/category.scss
  app/assets/stylesheets/scaffolds.scss
  app/javascript/components/ToolkitViewer.js
  app/views/layouts/_navbar.html.erb
  app/views/users/index.html.erb
  app/views/users/show.html.erb
  db/seeds.rb
  package-lock.json
  package.json
  yarn.lock
Labels: enhancement

#29 Test user controller
  .travis.yml
  Gemfile
  Gemfile.lock
  app/controllers/toolkit_controller.rb
  app/controllers/users_controller.rb
  features/admin_user.feature
  features/select_category.feature
  features/step_definitions/admin_steps.rb
  features/step_definitions/user_steps.rb
  features/support/paths.rb
  features/user_login.feature
  features/user_logout.feature
  features/user_profile_update.feature
  features/user_signup.feature
  spec/controllers/test_toolkit_controller_spec.rb
  spec/controllers/test_user_controller_spec.rb
  spec/factories.rb
  spec/rails_helper.rb
  spec/support/factory_bot.rb
Labels: test
